export const INVALID_PARAMETER 	= 'INVALID_PARAMETER';
export const UNAUTHORIZED 		 	= 'UNAUTHORIZED';
export const UNAUTHENTICATED 		 	= 'UNAUTHENTICATED';
export const PERMISSION_DENIED 	= 'PERMISSION_DENIED';
export const UNKNOWN_ERROR 			= 'UNKNOWN_ERROR';
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
